# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0002_auto_20160922_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(upload_to='statics/head_img'),
        ),
    ]
